//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reliability
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERI
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Lyambda { get; set; }
        public int IDClass { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
